name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "VisualStudio162019",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 16 2019",
            architecture: "-A x64"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -G "${{ matrix.config.generators }}" ${{ matrix.config.architecture }} -DLinAl_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_CXX_STANDARD=20

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.config.build_type }}
